### ISSUE TITLE
set hidpi but not work

### ISSUE THREAD

**Issue by link-duan** [usr-sse2/RDM#3]
I add a custom resolution and set hidpi.
Then restart. but hidpi with my resolution not work.

**Comment by usr-sse2** [comment]
Look - there is the half of your resolution with HiDPI ⚡️. Set up 2x larger resolution than you want, check HiDPI and you’ll get it

**Comment by chris1111** [comment]
hidpi is not working, I setup 1600x900 and 3200x1800
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu361.png)
Resolution is change only in RDM
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/sans_t56.png)

Also if I choose 1600x900 **⚡️**  the Dock icon is not sharpe
see 
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu362.png)
Here no **⚡️** Dock icon is Sharpe
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu357.png)

**Comment by usr-sse2** [comment]
@chris1111, I can't understand what you mean. What's the native resolution of your ProBook built-in display? 1366x768?

**Comment by chris1111** [comment]
> @chris1111, I can't understand what you mean. What's the native resolution of your ProBook built-in display? 1366x768?

Yes 1366x768
I mean hidpi with my resolution not work. Resolution is change only in RDM, not in preference System.

I also mean if I choose 1600x900 with lightning the dock icon is not perfectly clear

Iam on macOS Mojave 10.14.1

**Comment by usr-sse2** [comment]
@chris1111, on my ProBook 4520s (1366x768 too) the system rejects scaled resolutions for built-in display, even though I enabled HiDPI using `defaults` command. For the external TV it allows any resolutions. I thought that macOS doesn't allow scaling on small displays, but your example proves that it does O_o.

System Preferences by default list only 'recommended' resolutions. You can Option-click the `À l'échelle` item to get more (but still not all) resolutions. Notice that nothing is selected in the list, so System Preferences know that the current display mode is not in that list.

Your words that "dock icon is not perfectly clear" with HiDPI mode prove that HiDPI is working, because if you are upscaling, HiDPI makes it even worse. HiDPI makes image quality better when downscaling, e. g. 1280x800 ⚡️ on a 1920x1200 display.

You can take a screenshot with Cmd-Shift-3 in 1600x900 and 1600x900 ⚡️ modes and look at the pixel dimensions of the resulting files.

**Comment by chris1111** [comment]
Thanks
screenshot 1 no lightning
2,354,282 bytes (2.4 MB on disk)

screenshot 2 with lightning
6,805,457 bytes (6.8 MB on disk)
