### ISSUE TITLE
Duplicated frequency options

### ISSUE THREAD

**Issue by Olegt0rr** [usr-sse2/RDM#46]
- 59
- 59
<img width="232" alt="Screenshot 2021-11-13 at 09 33 07" src="https://user-images.githubusercontent.com/25399456/141608796-8d6fa2de-b40c-489b-a303-67fb2035bc1c.png">

**Comment by usr-sse2** [comment]
They may be different modes. 
1. Some displays (for example, Apple Pro Display XDR) support 59.94 Hz, and I'm not sure if it is represented as 59 or 60 Hz.
2. There can be different modes with equal parameters – for example, actual 1920x1080@60 (so that scaling is done by display, if requested in its own settings) and 1920x1080@60 scaled to the display's native resolution (so that scaling is managed by the OS). It is often encountered on HDMI-connected displays, because they include 1080p, 1080i and 720p modes in their EDID to conform to the HDMI specification.

If the actual refresh rate is different (case 1), then it can be fixed (but not easily, because the undocumented API that RDM is using now returns refresh rate as an integer value, so it's needed to find an alternative). How does [Display Maestro](https://www.koingosw.com/products/displaymaestro/) display your modes?

**Comment by usr-sse2** [comment]
Reproduced it myself. There are two modes 1600x900 HiDPI 60 Hz, and here are detailed properties from Display Maestro:
<img width="707" alt="Снимок экрана 2021-12-27 в 19 59 36" src="https://user-images.githubusercontent.com/446776/147492524-4bfbe0bb-9066-41f7-8a79-90cb8e64f212.png">
<img width="628" alt="Снимок экрана 2021-12-27 в 20 00 07" src="https://user-images.githubusercontent.com/446776/147492528-e2019fe8-c29b-402c-bfcc-175380236da5.png">
 
Display mode IDs are different, that means that they are different modes. The only different property is IO Flags.

I won't deduplicate these options, because if one mode works better with some display or one of them doesn't work at all, then deduplication may hide wrong one.
