### ISSUE TITLE
added custom hiDPI res -> computer won't boot anymore

### ISSUE THREAD

**Issue by asheenlevrai** [usr-sse2/RDM#6]
Hi,

I ran your version of RDM.
I selected edit to add a custom hiDPI res.
Saved (admin login required).
Rebooted - > computer wont boot.

How can I revert to the previous state?
Tx
-a-

PS:
 - machine: hackintosh (let me know if you need more info)
 - monitor native res. 3860x2160
 - added custom hiDPI res. 3360x1890

**Comment by usr-sse2** [comment]
What do you mean by 'won't boot'? Kernel panic, hang, system boots but no display?
If your display has no override plist bundled with macOS (most non-Apple displays don't have), you can boot into Recovery HD or single-user mode and remove the plist using the command line. Otherwise you need to restore the original plist.
What is your display's vendor ID and device ID? You can get them using the following command:
`ioreg -lw0 | grep IODisplayPrefsKey`
It will show a line like `    | |   | |         "IODisplayPrefsKey" = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@0/display0/AppleBacklightDisplay-30e4-360"`, where `30e4` is vendor ID and `360` is device ID.

**Comment by asheenlevrai** [comment]
Tx for the swift answer :)

I cannot reply before Monday. I was accessing the machine remotely.
Most probably boot hang (or KP), since the VNC server is unresponsive.
The only info I can give you right now is the display is Dell s2817q.

Can you please tell me where is located the plist file and what its name is?

I'll give you the remaining info on Monday morning.

Best,
-a-

PS:
Oh and I ran RDM from the desktop rather than from the App folder if this changes anything (I doubt it)

**Comment by usr-sse2** [comment]
`/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-vvvv/DisplayProductID-pppp`, where `vvvv` is the vendor ID and `pppp` is the product ID (device ID) of your display. This file has no extension.

**Comment by asheenlevrai** [comment]
Tx.

So I delete that file and I should be back to normal?

**Comment by asheenlevrai** [comment]
Hi,  I reached the machine this morning and boot was hung. However after rebooting everything took place normally.
The custom resolution was however not available. I will open another ticket about this topic.

Thanks
-a-
